### ISSUE TITLE
Please remove this repository

### ISSUE THREAD

**Issue by christopherzimmerman** [vlang/vnum#4]
I am not a fan of this being here, and I am even more against having it re-licensed under a different license, without even asking on the original repository.

If you bothered to read the license, you would see the following clause:

```
1. Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.
```

This is *not* being respected, given that the new license credits the "V Programming Language", and is now for some reason licensed under MIT?

The original repository states that work had paused until a stable release of `v` was available with working generics.  If you want to implement an n-dimensional container, feel free to take inspiration from `vnum`, but I would appreciate it not being a copy-paste of my work without even consulting me.

**Comment by medvednikov** [comment]
The original BSD license with the copyright was brought back.
